### ISSUE TITLE
Al editar un usuario, si no tienes cuidado, deja la clave en blanco.

### ISSUE THREAD

**Issue by ediazcomellas** [control-the-work/control-the-work#1]

**Comment by amieiro** [comment]
El problema que pude encontrar es que no se hacía un unset de la contraseña en blanco y, por lo tanto, se cambiaba la contraseña sin tener que hacerlo.
He resuelto el bug (https://github.com/control-the-work/control-the-work/commit/92f53a963d1a7a3b8a8280f80f918667b97e4d7e) y lo he desplegado en producción 
Cierro el issue.
Muchas gracias por reportarlo.
