### ISSUE TITLE
Los emails enmascaran la URL 

### ISSUE THREAD

**Issue by ediazcomellas** [control-the-work/control-the-work#2]
al crear un usuario o solicitar el reseteo de clave nos manda un link de confirmación:

El link parece ser: 

https://app.controlthework.com/email/verify/5ece9144-724f-11e9-8b?expires=15574683&signature=2f1258fdbab2b6fa9112688760b38ee037b....

Pero apunta a 

https://u10338090.ct.sendgrid.net/wf/click?upn=55qhVoHGij70IiqUDad....

Esto levanta avisos contra phishing.

**Comment by amieiro** [comment]
Era una configuración de tracking de SendGrid, el proveedor de correo transaccional. 
Acabo de desactivar esta característica y hacer una prueba con un restablecimiento de la contraseña. El correo llega correctamente, apuntando al enlace que tiene que ser:

https://app.controlthework.com/password/reset/ab5f2ebfe9f056874ea7dfcfb740f95cf12373680e270bf51b8d29811a753159

Gracias por el aviso. 
Cierro el issue.
