### ISSUE TITLE
Class 'Faker\Factory' not found 

### ISSUE THREAD

**Issue by sergiocarracedo** [control-the-work/control-the-work#3]
Installing using `composer install --no-dev` no install Faker and laler `php artisan migrate --seed` fails

**Comment by amieiro** [comment]
I have updated the .env.example file and the installation command to resolve this problem in the https://github.com/control-the-work/control-the-work/commit/1ab6d7d970947647dbe590f932b24d40feb4067c commit.

You can check some new installation information in the readme.md file.

Thank you for reporting the problem.

I close the issue.
